local text_original = LocalizationManager.text
function LocalizationManager:text(string_id, ...)
return string_id == "menu_st_spec_000" and "Burglar Free"
or string_id == "menu_st_spec_000_desc" and "Phien Ban Duoc Phat Trien Boi NamBoss. Http://mod.nguyennam.ml"
or string_id == "menu_deck7_1" and "Sneaky"
or string_id == "menu_deck7_1_desc" and "Your chance to dodge is increased by ##20%##"
or string_id == "menu_deck7_3" and "Bag of Tricks"
or string_id == "menu_deck7_3_desc" and "Standing still and crouching decreases your chances to be targeted by 10%. You bag corpses 20% faster."
or string_id == "menu_deck7_5" and "Luck of the Irish"
or string_id == "menu_deck7_5_desc" and "Your chance to dodge is increased by an additional 5%. Your chance to be targeted while standing still and crouching is decreased by an additional 5%. You pick locks 20% faster."
or string_id == "menu_deck7_7" and "Dutch Courage"
or string_id == "menu_deck7_7_desc" and  "Your chance to dodge is increased by an additional 5%. Your chance to be targeted while standing still and crouching is decreased by an additional 5%. You answer pagers 10% faster."
or string_id == "menu_deck7_9" and "Breath of Fresh Air"
or string_id == "menu_deck7_9_desc" and  "Standing still and crouching increases your armor recovery rate by 20%.\nYou gain 10% crouching movement speed."

or string_id == "menu_st_spec_001" and "Anarchist Free"
or string_id == "menu_st_spec_001_desc" and "Phien Ban Duoc Phat Trien Boi NamBoss. Http://mod.nguyennam.ml"
or string_id == "menu_deck15_1" and "Blitzkrieg Bop"
or string_id == "menu_deck15_1_desc" and "Instead of fully regenerating armor when out of combat, The Anarchist will continuously regenerate armor throughout the entire combat. Heavier armor regenerates more armor, but during longer intervals.\nWhen your armor gets depleted, you will be inmune to health damage for 2 seconds. This effect cannot occur more often than once every 15 seconds.\nNote: Skills and perks that increases the armor recovery rate are disabled when using this perk deck."
or string_id == "menu_deck15_3" and "straight edge"
or string_id == "menu_deck15_3_desc" and "50% of your health is converted into 100% armor."
or string_id == "menu_deck15_5" and "Death or Glory"
or string_id == "menu_deck15_5_desc" and "50% of your health is converted into 110% armor."
or string_id == "menu_deck15_7" and "Rise Above"
or string_id == "menu_deck15_7_desc" and  "50% of your health is converted into 120% armor."
or string_id == "menu_deck15_9" and "Lust for Life"
or string_id == "menu_deck15_9_desc" and  "Dealing damage will grant you 10 armor - this can only occur once every 1.5 seconds.\nNote: Despite saying 10, it has always granted 30 armor."

or string_id == "menu_st_spec_002" and "Sociopath Free"
or string_id == "menu_st_spec_002_desc" and "Phien Ban Duoc Phat Trien Boi NamBoss. Http://mod.nguyennam.ml"
or string_id == "menu_deck9_1" and "OVERDOG"
or string_id == "menu_deck9_1_desc" and "When you are surrounded by three enemies or more, you receive 12% less damage from enemies.\nYour second and each consecutive melee hit within 1 second of the last one will deal 10 times its normal damage.\nNote: Missing a melee strike resets the buff. The buff can be activated on team AI and civilians."
or string_id == "menu_deck9_3" and "Tension"
or string_id == "menu_deck9_3_desc" and "Killing an enemy regenerates 30 armor.\nThis cannot occur more than once every 1 second.\nYou gain an additional 10% armor."
or string_id == "menu_deck9_5" and "Clean Hit"
or string_id == "menu_deck9_5_desc" and "Killing an enemy with a melee weapon regenerates 10% health.\nThis cannot occur more than once every 1 second.\nWhen you are within medium range of an enemy you recieve 8% less damage."
or string_id == "menu_deck9_7" and "Overdose"
or string_id == "menu_deck9_7_desc" and  "Killing an enemy at medium range recovers 30 armor.\nThis cannot occur more than once every 1 seconds.\nYou gain an additional 10% armor."
or string_id == "menu_deck9_9" and "Showdown"
or string_id == "menu_deck9_9_desc" and  "Killing an enemy at medium range has a 75% chance to spread panic among your enemies.\nPanic will make enemies go into short bursts of uncontrollable fear.\nThis cannot occur more than once every 1 second."

or string_id == "menu_st_spec_003" and "Yakuza Free"
or string_id == "menu_st_spec_003_desc" and "Phien Ban Duoc Phat Trien Boi NamBoss. Http://mod.nguyennam.ml"
or string_id == "menu_deck12_1" and "Koi Irezumi"
or string_id == "menu_deck12_1_desc" and "The lower your health, the more armor recovery rate you have. When your health is below 50%, you will gain up to 20% armor recovery rate.\nEntering this state negates regeneration effects. Bonuses scale linearly with health."
or string_id == "menu_deck12_3" and "Hebi Irezumi"
or string_id == "menu_deck12_3_desc" and "The lower your health, the more movement speed you gain. When your health is below 50%, you will gain up to 20% movement speed."
or string_id == "menu_deck12_5" and "Tora Irezumi"
or string_id == "menu_deck12_5_desc" and "The lower your health, the more armor recovery rate you have. When your health is below 50%, you will gain up to an additional 20% armor recovery rate."
or string_id == "menu_deck12_7" and "Ryu Irezumi"
or string_id == "menu_deck12_7_desc" and  "The lower your health, the more armor recovery rate you have. When your health is below 50%, you will gain up to an additional 20% armor recovery rate."
or string_id == "menu_deck12_9" and "Oni Irezumi"
or string_id == "menu_deck12_9_desc" and  "All berserker effects in this perk deck will start at 100% health instead of 50%."

or string_id == "menu_st_spec_004" and "Grinder Free"
or string_id == "menu_st_spec_004_desc" and "Phien Ban Duoc Phat Trien Boi NamBoss. Http://mod.nguyennam.ml"
or string_id == "menu_deck11_1" and "Histamine"
or string_id == "menu_deck11_1_desc" and "Damaging an enemy heals 1 life points every 0.3 seconds for 3 seconds.\nThis effect stacks but cannot occur more than once every 1.5 seconds, and only while wearing the Two-piece Suit or Lightweight Ballistic Vest."
or string_id == "menu_deck11_3" and "Adrenaline"
or string_id == "menu_deck11_3_desc" and "Damaging an enemy now heals 2 life points every 0.3 seconds for 3 seconds.\nYou gain 20% more health."
or string_id == "menu_deck11_5" and "Endorphins"
or string_id == "menu_deck11_5_desc" and "Damaging an enemy now heals 3 life points every 0.3 seconds for 3 seconds.\nIncrease your chance to pierce enemy armor by 10%."
or string_id == "menu_deck11_7" and "Dopamine"
or string_id == "menu_deck11_7_desc" and  "Damaging an enemy now heals 4 life points every 0.3 seconds for 3 seconds.\nYou gain 20% more health."
or string_id == "menu_deck11_9" and "Euphoria"
or string_id == "menu_deck11_9_desc" and  "Damaging an enemy now heals 4 life points every 0.3 seconds for 4.2 seconds.\nIncrease your chance to pierce enemy armor by 20%."

or string_id == "menu_st_spec_005" and "Shotgun Izdabest"
or string_id == "menu_st_spec_005_desc" and "Phien Ban Duoc Phat Trien Boi NamBoss. Http://mod.nguyennam.ml"
or string_id == "menu_deck41_1" and "Subtle"
or string_id == "menu_deck41_1_desc" and "Add ##15%## dodge"
or string_id == "menu_deck41_3" and "Elusive"
or string_id == "menu_deck41_3_desc" and "Giam ##-15%## targeted"
or string_id == "menu_deck41_5" and "Evasive"
or string_id == "menu_deck41_5_desc" and "Add ##15%## dodge"
or string_id == "menu_deck41_7" and "Shadow Warrior"
or string_id == "menu_deck41_7_desc" and  "Add ##15%## dodge"
or string_id == "menu_deck41_9" and "Boost"
or string_id == "menu_deck41_9_desc" and  "Add ##8## stability for Shotgun. \n\n Add ##5%## damage forcho shotgun. \n\n Add ##25%## ammo."

or string_id == "menu_st_spec_006" and "Akimbo Izdabest"
or string_id == "menu_st_spec_006_desc" and "Phien Ban Duoc Phat Trien Boi NamBoss. Http://mod.nguyennam.ml"
or string_id == "menu_deck42_1" and "Subtle"
or string_id == "menu_deck42_1_desc" and "Add ##15%## dodge"
or string_id == "menu_deck42_3" and "Elusive"
or string_id == "menu_deck42_3_desc" and "Giam ##-15%## targeted"
or string_id == "menu_deck42_5" and "Evasive"
or string_id == "menu_deck42_5_desc" and "Add ##15%## dodge"
or string_id == "menu_deck42_7" and "Shadow Warrior"
or string_id == "menu_deck42_7_desc" and  "Add ##15%## dodge"
or string_id == "menu_deck42_9" and "Boost"
or string_id == "menu_deck42_9_desc" and  "Add ##16## stability for Akimbo. \n\n Add ##50%## ammo. \n\n Add ##35%## pickup rate."

or string_id == "menu_st_spec_007" and "Assassin's Creed"
or string_id == "menu_st_spec_007_desc" and "Phien Ban Duoc Phat Trien Boi NamBoss. Http://mod.nguyennam.ml"
or string_id == "menu_deck43_1" and "Khoi Dau"
or string_id == "menu_deck43_1_desc" and "Add ##15%## dodge"
or string_id == "menu_deck43_3" and "Ninja"
or string_id == "menu_deck43_3_desc" and "Giam ##-15%## targeted when standing near teammates. \n\n Add ##25%## toc do hoi suc khi chay."
or string_id == "menu_deck43_5" and "An tron"
or string_id == "menu_deck43_5_desc" and "Tang ##1%## dodge cu moi ##3## diem risk duoi ##35## (Max 10 diem toi da) "
or string_id == "menu_deck43_7" and "Tang Hinh"
or string_id == "menu_deck43_7_desc" and  "The enemy will attack you less ##15%##. \n\n Add ##100%## damage Melee."
or string_id == "menu_deck43_9" and "Vo Danh"
or string_id == "menu_deck43_9_desc" and  "The enemy will attack you less ##20%##.\n\n Add ##30%## movement speed after rescuing teammates ##10s##. \n\n Without blood and armor ##4s## you will get ##35%## crit in ##6s##."

or string_id == "menu_deckall_2" and "Helmet Popper"
or string_id == "menu_deckall_2_desc" and "Increases your headshot damage by ##25%##."
or string_id == "menu_deckall_4" and "Blending In"
or string_id == "menu_deckall_4_desc" and "You gain +1 increased concealment.\nWhen wearing armor, your movement speed is ##15%## less affected.\nYou gain ##45%## more experience when you complete days and jobs."
or string_id == "menu_deckall_6" and "Walk-in Closet"
or string_id == "menu_deckall_6_desc" and "Unlocks an armor bag equipment for you to use. The armor bag can be used to change your armor during a heist.\nIncreases your ammo pickup to ##135%## of the normal rate."
or string_id == "menu_deckall_8" and "Fast and Furious"
or string_id == "menu_deckall_8_desc" and "You deal ##5%## more damage. Does not apply to melee damage, throwables, grenade launchers, crossbows, and the HRL-7 Rocket Launcher.\nIncreases your doctor bag interaction speed by ##20%##."

or string_id == "menu_st_spec_21" and "Burglar"
or string_id == "menu_st_spec_22" and "Anarchist"
or string_id == "menu_st_spec_23" and "Sociopath"
or string_id == "menu_st_spec_24" and "Yakuza"
or string_id == "menu_st_spec_25" and "Grinder"
or string_id == "menu_st_spec_26" and "Shotgun Izdabest"
or string_id == "menu_st_spec_27" and "Akimbo Izdabest"
or string_id == "menu_st_spec_28" and "Assassin's Creed"
or text_original(self, string_id, ...)
end